### ISSUE TITLE
[BUG] docker create volume for V9K error with "Unmarshal"

### ISSUE THREAD

**Issue by YuDaiWang** [IBM/ubiquity#44]
When I create volume  with command "docker volume create --driver ubiquity --name volumeqqqq --opt size=5 --opt profile=gold",  I check the storage side, the volume is indeed created. But get an error.
there is an  error in ubiquity log below:
![create volume error](https://user-images.githubusercontent.com/28969890/27218670-8dd059d8-52b1-11e7-93ab-52f3dab6e131.jpg)

**Comment by shay-berman** [comment]
Hi @YuDaiWang, thanks for catching this out.
Fixed the issue(description of the fix can see in the commit message cd5139b), please verify it and then move the ticket to done if it works on V9000.
Thanks

**Comment by YuDaiWang** [comment]
Still get a unmarshal error:
Error response from daemon: create wydtest1: VolumeDriver.Create: json: cannot unmarshal number into Go value of type string
I try to convert the data, get the error:
json: cannot unmarshal number into Go struct field ScbeResponseVolume.copy_count of type string

**Comment by shay-berman** [comment]
fixed it now (see the commit message 	0f9c797)
@YuDaiWang, please validate

**Comment by YuDaiWang** [comment]
Verified

**Comment by shay-berman** [comment]
thanks @yudainwang
